#!/usr/bin/tclsh
# This file defines the set of scripts (rules) that should be executed
# by default (if no specific profile is named when vera++ is launched).

set rules {
    F001

    L001
    L002
    L003
    L004
    L005
    L006

    PSQ001
    PSQ002

    T001
    T002
    PSQ004
    T005
    T006
    T007
    T008
    T009
    T010
    PSQ011
    T013
    T015
    PSQ016
    T017
    T018
}
